<a href="https://colab.research.google.com/github/jennyschilling/project_voting_group11/blob/main/data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! rm -r project_voting_group11/

rm: cannot remove 'project_voting_group11/': No such file or directory

In [2]:
!git clone https://github.com/jennyschilling/project_voting_group11

Cloning into 'project_voting_group11'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 102 (delta 10), reused 6 (delta 6), pack-reused 84
Receiving objects: 100% (102/102), 35.08 MiB | 19.31 MiB/s, done.
Resolving deltas: 100% (40/40), done.

In [3]:
import pandas as pd
import numpy as np

In [4]:
demographics_data = pd.read_csv('/content/project_voting_group11/data/va_2016-20_demographics.csv')
voting_data = pd.read_csv('/content/project_voting_group11/data/voting_VA_2020.csv')

(demographics_data.head(), voting_data.head())

(    GISJOIN       YEAR STUSAB  REGIONA  DIVISIONA     STATE  STATEA  \
 0  G5100010  2016-2020     VA      NaN        NaN  Virginia      51
 1  G5100030  2016-2020     VA      NaN        NaN  Virginia      51
 2  G5100050  2016-2020     VA      NaN        NaN  Virginia      51
 3  G5100070  2016-2020     VA      NaN        NaN  Virginia      51
 4  G5100090  2016-2020     VA      NaN        NaN  Virginia      51

              COUNTY  COUNTYA  COUSUBA  ...  AM8FE031  AM8FE032  AM8FE033  \
 0   Accomack County        1      NaN  ...      6474       823      5651
 1  Albemarle County        3      NaN  ...     20763      1248     19515
 2  Alleghany County        5      NaN  ...      3052       523      2529
 3     Amelia County        7      NaN  ...      2667       379      2288
 4    Amherst County        9      NaN  ...      6596       771      5825

    AM8FE034  AM8FE035  AM8FE036  AM8FE037  AM8FE038  AM8FE039  AM9SE001
 0      2376       426      1950      1683       920       763    0.4562
 1      6183       723      5460      4898      2124      2774    0.4719
 2      1071       288       783       836       442       394    0.4537
 3       746       114       632       570       265       305    0.4320
 4      2009       472      1537      1636       695       941    0.4239

 [5 rows x 161 columns],
    Unnamed: 0  year     state state_po county_name  county_fips        office  \
 0       70379  2020  VIRGINIA       VA    ACCOMACK        51001  US PRESIDENT
 1       70380  2020  VIRGINIA       VA    ACCOMACK        51001  US PRESIDENT
 2       70381  2020  VIRGINIA       VA    ACCOMACK        51001  US PRESIDENT
 3       70382  2020  VIRGINIA       VA    ACCOMACK        51001  US PRESIDENT
 4       70383  2020  VIRGINIA       VA    ACCOMACK        51001  US PRESIDENT

            candidate        party  candidatevotes  totalvotes   version  \
 0  JOSEPH R BIDEN JR     DEMOCRAT            5495       16962  20220315
 1  JOSEPH R BIDEN JR     DEMOCRAT            2072       16962  20220315
 2  JOSEPH R BIDEN JR     DEMOCRAT              11       16962  20220315
 3       JO JORGENSEN  LIBERTARIAN              66       16962  20220315
 4       JO JORGENSEN  LIBERTARIAN             122       16962  20220315

            mode
 0      ABSENTEE
 1  ELECTION DAY
 2   PROVISIONAL
 3      ABSENTEE
 4  ELECTION DAY  )

In [5]:
# We need to merge these two files on the county names, so we have to get the names
# formatted in the same manner first
def format_county_name(county_name):
    county_name = county_name.replace(" County", "")
    return county_name.upper()

demographics_data['COUNTY'] = demographics_data['COUNTY'].apply(format_county_name)
demographics_data.head()

,GISJOIN,YEAR,STUSAB,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,...,AM8FE031,AM8FE032,AM8FE033,AM8FE034,AM8FE035,AM8FE036,AM8FE037,AM8FE038,AM8FE039,AM9SE001
0,G5100010,2016-2020,VA,NaN,NaN,Virginia,51,ACCOMACK,1,NaN,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
1,G5100030,2016-2020,VA,NaN,NaN,Virginia,51,ALBEMARLE,3,NaN,...,20763,1248,19515,6183,723,5460,4898,2124,2774,0.4719
2,G5100050,2016-2020,VA,NaN,NaN,Virginia,51,ALLEGHANY,5,NaN,...,3052,523,2529,1071,288,783,836,442,394,0.4537
3,G5100070,2016-2020,VA,NaN,NaN,Virginia,51,AMELIA,7,NaN,...,2667,379,2288,746,114,632,570,265,305,0.4320
4,G5100090,2016-2020,VA,NaN,NaN,Virginia,51,AMHERST,9,NaN,...,6596,771,5825,2009,472,1537,1636,695,941,0.4239

In [6]:
# Now we can merge the two datasets on the county name
merged_df = pd.merge(voting_data, demographics_data, left_on='county_name', right_on='COUNTY')
merged_df.to_csv('./project_voting_group11/data/merged.csv', index=False)
merged_df.head()

,Unnamed: 0,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,...,AM8FE031,AM8FE032,AM8FE033,AM8FE034,AM8FE035,AM8FE036,AM8FE037,AM8FE038,AM8FE039,AM9SE001
0,70379,2020,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,5495,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
1,70380,2020,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,2072,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
2,70381,2020,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,11,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
3,70382,2020,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,66,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562
4,70383,2020,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,122,...,6474,823,5651,2376,426,1950,1683,920,763,0.4562

In [7]:
for column in merged_df.columns:
  print("column = ", column)
  print("type = ", merged_df[column].dtype)
  print(merged_df[column].unique())
  print("----------------------")
  print("----------------------")

column =  Unnamed: 0
type =  int64
[70379 70380 70381 ... 71968 71969 71970]
----------------------
----------------------
column =  year
type =  int64
[2020]
----------------------
----------------------
column =  state
type =  object
['VIRGINIA']
----------------------
----------------------
column =  state_po
type =  object
['VA']
----------------------
----------------------
column =  county_name
type =  object
['ACCOMACK' 'ALBEMARLE' 'ALLEGHANY' 'AMELIA' 'AMHERST' 'APPOMATTOX'
 'ARLINGTON' 'AUGUSTA' 'BATH' 'BEDFORD' 'BLAND' 'BOTETOURT' 'BRUNSWICK'
 'BUCHANAN' 'BUCKINGHAM' 'CAMPBELL' 'CAROLINE' 'CARROLL' 'CHARLES CITY'
 'CHARLOTTE' 'CHESTERFIELD' 'CLARKE' 'CRAIG' 'CULPEPER' 'CUMBERLAND'
 'DICKENSON' 'DINWIDDIE' 'ESSEX' 'FAIRFAX' 'FAUQUIER' 'FLOYD' 'FLUVANNA'
 'FRANKLIN' 'FREDERICK' 'GILES' 'GLOUCESTER' 'GOOCHLAND' 'GRAYSON'
 'GREENE' 'GREENSVILLE' 'HALIFAX' 'HANOVER' 'HENRICO' 'HENRY' 'HIGHLAND'
 'ISLE OF WIGHT' 'JAMES CITY' 'KING AND QUEEN' 'KING GEORGE'
 'KING WILLIAM' 'LANCASTER' 'LEE' 'LOUDOUN' 'LOUISA' 'LUNENBURG' 'MADISON'
 'MATHEWS' 'MECKLENBURG' 'MIDDLESEX' 'MONTGOMERY' 'NELSON' 'NEW KENT'
 'NORTHAMPTON' 'NORTHUMBERLAND' 'NOTTOWAY' 'ORANGE' 'PAGE' 'PATRICK'
 'PITTSYLVANIA' 'POWHATAN' 'PRINCE EDWARD' 'PRINCE GEORGE'
 'PRINCE WILLIAM' 'PULASKI' 'RAPPAHANNOCK' 'RICHMOND' 'ROANOKE'
 'ROCKBRIDGE' 'ROCKINGHAM' 'RUSSELL' 'SCOTT' 'SHENANDOAH' 'SMYTH'
 'SOUTHAMPTON' 'SPOTSYLVANIA' 'STAFFORD' 'SURRY' 'SUSSEX' 'TAZEWELL'
 'WARREN' 'WASHINGTON' 'WESTMORELAND' 'WISE' 'WYTHE' 'YORK'
 'ALEXANDRIA CITY' 'BRISTOL CITY' 'BUENA VISTA CITY'
 'CHARLOTTESVILLE CITY' 'CHESAPEAKE CITY' 'COLONIAL HEIGHTS CITY'
 'COVINGTON CITY' 'DANVILLE CITY' 'EMPORIA CITY' 'FAIRFAX CITY'
 'FALLS CHURCH CITY' 'FRANKLIN CITY' 'FREDERICKSBURG CITY' 'GALAX CITY'
 'HAMPTON CITY' 'HARRISONBURG CITY' 'HOPEWELL CITY' 'LEXINGTON CITY'
 'LYNCHBURG CITY' 'MANASSAS CITY' 'MANASSAS PARK CITY' 'MARTINSVILLE CITY'
 'NEWPORT NEWS CITY' 'NORFOLK CITY' 'NORTON CITY' 'PETERSBURG CITY'
 'POQUOSON CITY' 'PORTSMOUTH CITY' 'RADFORD CITY' 'RICHMOND CITY'
 'ROANOKE CITY' 'SALEM CITY' 'STAUNTON CITY' 'SUFFOLK CITY'
 'VIRGINIA BEACH CITY' 'WAYNESBORO CITY' 'WILLIAMSBURG CITY'
 'WINCHESTER CITY']
----------------------
----------------------
column =  county_fips
type =  int64
[51001 51003 51005 51007 51009 51011 51013 51015 51017 51019 51021 51023
 51025 51027 51029 51031 51033 51035 51036 51037 51041 51043 51045 51047
 51049 51051 51053 51057 51059 51061 51063 51065 51067 51069 51071 51073
 51075 51077 51079 51081 51083 51085 51087 51089 51091 51093 51095 51097
 51099 51101 51103 51105 51107 51109 51111 51113 51115 51117 51119 51121
 51125 51127 51131 51133 51135 51137 51139 51141 51143 51145 51147 51149
 51153 51155 51157 51159 51161 51163 51165 51167 51169 51171 51173 51175
 51177 51179 51181 51183 51185 51187 51191 51193 51195 51197 51199 51510
 51520 51530 51540 51550 51570 51580 51590 51595 51600 51610 51620 51630
 51640 51650 51660 51670 51678 51680 51683 51685 51690 51700 51710 51720
 51730 51735 51740 51750 51760 51770 51775 51790 51800 51810 51820 51830
 51840]
----------------------
----------------------
column =  office
type =  object
['US PRESIDENT']
----------------------
----------------------
column =  candidate
type =  object
['JOSEPH R BIDEN JR' 'JO JORGENSEN' 'OTHER' 'DONALD J TRUMP']
----------------------
----------------------
column =  party
type =  object
['DEMOCRAT' 'LIBERTARIAN' 'OTHER' 'REPUBLICAN']
----------------------
----------------------
column =  candidatevotes
type =  int64
[  5495   2072     11     66    122      0     12   3084   6078     10
  33416   8716    334    492    517      5    210    159      4   9124
  11587     93   1250    993     24     65      8   1450   4409   1719
    673     19     37     42      1      9      3   2595   2778     17
   3871   1746     55     86    164   4487   6550   1565    850     47
     71   2995   3700      7  91963  13081    300   1168    662      6
    823    405     13  13899   8306    113   7874   2911    256    346
     61  12866  17741    107    358    288      2    399   1431   8705
   3346    125    303    393     87     98  15208  20268    124    313
    218     18     22    976   1925   4231   1455     14    120    144
     34     26   7212   7875   2807   1745   1368   1988    768    815
   2306   5981   2285   1181     39     54   1795   2744   5536   2534
    180    310     50     46   9331  11914   4957   2648     52     84
    175   2839   5438     59   1740   1078     33     82     27   3909
   8706     44   2024    592     21    811    947   1532    785   1390
   2423  85505  21006    424   1591   1312    473    290  57160  35939
    227   3121    791     90     88     20   2554   2632    273     30
    804   1721   8016   2543     58    191    209     36     45   6836
   9131   1422    803   1039   1974   1030   2462   3285   4265   1944
     15     85   3982   4709   2131    899     32   1736   1334 321219
  96479   2245   4217   3741     56   2768   2078  84585  82873    943
  14131   3341    418    354    140     83  13573  11441     92   2524
    466     91   2851   3347   6083   1290     41    131     35   4248
   3865   5368   2979    115    236   6670  14168     57  13101   3944
    162    363    416    101     69  15219  15164   1443    713     43
   2754   4122   4993   1943     28    168    220     31   6267   8588
   5260   1410    114    128   5393   4548     25    987    544   2146
   4366   3343    809    109   3558   3291   1353   1274    658   1256
   5551   2097     64     76   4844   5559  19046   6148    588    510
    141    116  23708  20535     75  81563  34294    715   1002   1389
     23    461    404  27296  35823    321   6395   2665     67    132
     16   6911   9743    233    184    237    853   6891   2455     53
    146    182   6487   7174  21882   3524    147    427    278    169
  14707   8385    984    601    887   1560   4376   1014    192    121
   5182   3251   2054   1174     38    102   2735   4549   2478     29
   1687   2010    761    724     60   2214   6146 109335  28492    545
   1807   1321    830    540  44292  37545    251   6092   2135    117
    176   5313   7950   1495    911   1354   2181   1911    779   1856
   3441   1561    262   2619   1277   4150   2617     72   4111   5133
   1788    696     49   1664   2520  18499   4654    472    465    103
   9479  11109   3204   1117   1525   3279   3143   1451     70   2989
   6611   2814    840     40   1623   1325   2467    773   2269   2208
   1945   1026   1968   2059   5510   2453     99   4252   8149   2149
    833   2895   6421   1197    753     51   2439   5038   6414   3640
    134    150  11590  12104   3781   1528    129   6162   3048   1897
   1810   2620   5101   2002     79   5080   5023 114350  27596    917
   2006   1203    881  52887  27939    396   3526   1367    104    170
   5300   6783   1470    609    639   2155   1083    430   1253   1294
  17550   4196    463    444  19279  14913   2836   1232   2187   5881
   8527   4070    217    436     78     96   9267  21030   1375    991
     48   3939   6917    978    707   3588   5458   4729   2052    139
    204  10315   1694   1314     81   2925   8038   2341   1607   2102
   3617  26829   7474    655    646    167  20997  18410  30218   9810
    674    190    178  18509  19004    123   1722    885   1138   1357
    801   1418   2219    972   7682   9013   4959   1605    155    207
   6296   7737   5122   1480    137    165  10595  11051   3086   2125
   3160   2172    926   6984   6355   2065     62    108   7751  14654
   2913    374    305  12902   7286  55940   9973    327    378    240
   8951   5496     97    554     63   2898   2433    637    188   1128
    735  16289   4294    138    171   1399   1676  53788  12268   1120
    958    417    172  35502  22440    238   2095    870   3577   2422
    578    386   1070   7555   4060     95     74    119   4186   3210
    796    816    244   7610   1510   2374   1608   6481    648    509
   1615    890    737    746   6529   1930   2202   1819    537    886
    948  35251  10634    335    471    519   9386   8924   8254   2701
    181    179   2830   2715   3388   1975     89   1964   2021   1574
    211    515    389  11985   5947    281    572    213   5746  11269
   8007   2286   3760   2468   3137    834   1239    733   2624   1125
   1096   1068  35999  16655    445    622    805  11557  14705  45563
  18270    607    751    843    285    198  11652  11651   1106   8421
   3891     77    856    719   1635   2299  19680  10964    304   4281
   8401     73   2324   1018   1304   1477  63694  27809    672    336
    373   7533   8967  19780   6501    429     80   7594   7856    157
   4211    932    111   4710   2966   5813   1158   3053   2616  20922
   7557    197    343    380   9474  10532  81003  35431    959   1665
   2503    507    513  47179  57327    581   3799   1133   2866   4035
    721   1341    615   5093   1466   2825   2370]
----------------------
----------------------
column =  totalvotes
type =  int64
[ 16962  64657   8203   7894  17005   9268 130739  42278   2501  48669
   3479  21123   7948   9957   8129  29901  16288  15657   4441   6191
 203955   9337   3170  27116   5313   7307  15092   6178 601243  43671
   9412  15846  29704  48718   9178  22284  16952   8131  11313   4574
  18248  70988 183299  26105   1533  23456  49639   4115  14227  10737
   7152   9947 224976  21916   6002   8133   5829  16207   6785  45037
   9318  14471   6732   7815   7078  20754  12514   9535  34227  19733
   9575  17439 228267  17386   4979   4102  57226  12377  43821  13386
  10869  23684  14136   9786  75317  79629   4471   5088  20152  21147
  28693   9948  16615  15073  38791  82521   7814   2776  24213 127246
   9160   2603  19456   2384  13487   8819   4064  12877   2639  65957
  17093   9628   2764  36364  16978   6088   6024  81270  89988   1601
  14133   7857  44601   6320 111181  43323  13051  12992  49642 227717
  10717   6890  12113]
----------------------
----------------------
column =  version
type =  int64
[20220315]
----------------------
----------------------
column =  mode
type =  object
['ABSENTEE' 'ELECTION DAY' 'PROVISIONAL']
----------------------
----------------------
column =  GISJOIN
type =  object
['G5100010' 'G5100030' 'G5100050' 'G5100070' 'G5100090' 'G5100110'
 'G5100130' 'G5100150' 'G5100170' 'G5100190' 'G5100210' 'G5100230'
 'G5100250' 'G5100270' 'G5100290' 'G5100310' 'G5100330' 'G5100350'
 'G5100360' 'G5100370' 'G5100410' 'G5100430' 'G5100450' 'G5100470'
 'G5100490' 'G5100510' 'G5100530' 'G5100570' 'G5100590' 'G5100610'
 'G5100630' 'G5100650' 'G5100670' 'G5100690' 'G5100710' 'G5100730'
 'G5100750' 'G5100770' 'G5100790' 'G5100810' 'G5100830' 'G5100850'
 'G5100870' 'G5100890' 'G5100910' 'G5100930' 'G5100950' 'G5100970'
 'G5100990' 'G5101010' 'G5101030' 'G5101050' 'G5101070' 'G5101090'
 'G5101110' 'G5101130' 'G5101150' 'G5101170' 'G5101190' 'G5101210'
 'G5101250' 'G5101270' 'G5101310' 'G5101330' 'G5101350' 'G5101370'
 'G5101390' 'G5101410' 'G5101430' 'G5101450' 'G5101470' 'G5101490'
 'G5101530' 'G5101550' 'G5101570' 'G5101590' 'G5101610' 'G5101630'
 'G5101650' 'G5101670' 'G5101690' 'G5101710' 'G5101730' 'G5101750'
 'G5101770' 'G5101790' 'G5101810' 'G5101830' 'G5101850' 'G5101870'
 'G5101910' 'G5101930' 'G5101950' 'G5101970' 'G5101990' 'G5105100'
 'G5105200' 'G5105300' 'G5105400' 'G5105500' 'G5105700' 'G5105800'
 'G5105900' 'G5105950' 'G5106000' 'G5106100' 'G5106200' 'G5106300'
 'G5106400' 'G5106500' 'G5106600' 'G5106700' 'G5106780' 'G5106800'
 'G5106830' 'G5106850' 'G5106900' 'G5107000' 'G5107100' 'G5107200'
 'G5107300' 'G5107350' 'G5107400' 'G5107500' 'G5107600' 'G5107700'
 'G5107750' 'G5107900' 'G5108000' 'G5108100' 'G5108200' 'G5108300'
 'G5108400']
----------------------
----------------------
column =  YEAR
type =  object
['2016-2020']
----------------------
----------------------
column =  STUSAB
type =  object
['VA']
----------------------
----------------------
column =  REGIONA
type =  float64
[nan]
----------------------
----------------------
column =  DIVISIONA
type =  float64
[nan]
----------------------
----------------------
column =  STATE
type =  object
['Virginia']
----------------------
----------------------
column =  STATEA
type =  int64
[51]
----------------------
----------------------
column =  COUNTY
type =  object
['ACCOMACK' 'ALBEMARLE' 'ALLEGHANY' 'AMELIA' 'AMHERST' 'APPOMATTOX'
 'ARLINGTON' 'AUGUSTA' 'BATH' 'BEDFORD' 'BLAND' 'BOTETOURT' 'BRUNSWICK'
 'BUCHANAN' 'BUCKINGHAM' 'CAMPBELL' 'CAROLINE' 'CARROLL' 'CHARLES CITY'
 'CHARLOTTE' 'CHESTERFIELD' 'CLARKE' 'CRAIG' 'CULPEPER' 'CUMBERLAND'
 'DICKENSON' 'DINWIDDIE' 'ESSEX' 'FAIRFAX' 'FAUQUIER' 'FLOYD' 'FLUVANNA'
 'FRANKLIN' 'FREDERICK' 'GILES' 'GLOUCESTER' 'GOOCHLAND' 'GRAYSON'
 'GREENE' 'GREENSVILLE' 'HALIFAX' 'HANOVER' 'HENRICO' 'HENRY' 'HIGHLAND'
 'ISLE OF WIGHT' 'JAMES CITY' 'KING AND QUEEN' 'KING GEORGE'
 'KING WILLIAM' 'LANCASTER' 'LEE' 'LOUDOUN' 'LOUISA' 'LUNENBURG' 'MADISON'
 'MATHEWS' 'MECKLENBURG' 'MIDDLESEX' 'MONTGOMERY' 'NELSON' 'NEW KENT'
 'NORTHAMPTON' 'NORTHUMBERLAND' 'NOTTOWAY' 'ORANGE' 'PAGE' 'PATRICK'
 'PITTSYLVANIA' 'POWHATAN' 'PRINCE EDWARD' 'PRINCE GEORGE'
 'PRINCE WILLIAM' 'PULASKI' 'RAPPAHANNOCK' 'RICHMOND' 'ROANOKE'
 'ROCKBRIDGE' 'ROCKINGHAM' 'RUSSELL' 'SCOTT' 'SHENANDOAH' 'SMYTH'
 'SOUTHAMPTON' 'SPOTSYLVANIA' 'STAFFORD' 'SURRY' 'SUSSEX' 'TAZEWELL'
 'WARREN' 'WASHINGTON' 'WESTMORELAND' 'WISE' 'WYTHE' 'YORK'
 'ALEXANDRIA CITY' 'BRISTOL CITY' 'BUENA VISTA CITY'
 'CHARLOTTESVILLE CITY' 'CHESAPEAKE CITY' 'COLONIAL HEIGHTS CITY'
 'COVINGTON CITY' 'DANVILLE CITY' 'EMPORIA CITY' 'FAIRFAX CITY'
 'FALLS CHURCH CITY' 'FRANKLIN CITY' 'FREDERICKSBURG CITY' 'GALAX CITY'
 'HAMPTON CITY' 'HARRISONBURG CITY' 'HOPEWELL CITY' 'LEXINGTON CITY'
 'LYNCHBURG CITY' 'MANASSAS CITY' 'MANASSAS PARK CITY' 'MARTINSVILLE CITY'
 'NEWPORT NEWS CITY' 'NORFOLK CITY' 'NORTON CITY' 'PETERSBURG CITY'
 'POQUOSON CITY' 'PORTSMOUTH CITY' 'RADFORD CITY' 'RICHMOND CITY'
 'ROANOKE CITY' 'SALEM CITY' 'STAUNTON CITY' 'SUFFOLK CITY'
 'VIRGINIA BEACH CITY' 'WAYNESBORO CITY' 'WILLIAMSBURG CITY'
 'WINCHESTER CITY']
----------------------
----------------------
column =  COUNTYA
type =  int64
[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  36  37  41  43  45  47  49  51  53  57  59  61  63  65  67  69  71  73
  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109
 111 113 115 117 119 121 125 127 131 133 135 137 139 141 143 145 147 149
 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181 183 185 187
 191 193 195 197 199 510 520 530 540 550 570 580 590 595 600 610 620 630
 640 650 660 670 678 680 683 685 690 700 710 720 730 735 740 750 760 770
 775 790 800 810 820 830 840]
----------------------
----------------------
column =  COUSUBA
type =  float64
[nan]
----------------------
----------------------
column =  PLACEA
type =  float64
[nan]
----------------------
----------------------
column =  TRACTA
type =  float64
[nan]
----------------------
----------------------
column =  CONCITA
type =  float64
[nan]
----------------------
----------------------
column =  AIANHHA
type =  float64
[nan]
----------------------
----------------------
column =  RES_ONLYA
type =  float64
[nan]
----------------------
----------------------
column =  TRUSTA
type =  float64
[nan]
----------------------
----------------------
column =  AIHHTLI
type =  float64
[nan]
----------------------
----------------------
column =  AITSCEA
type =  float64
[nan]
----------------------
----------------------
column =  ANRCA
type =  float64
[nan]
----------------------
----------------------
column =  CBSAA
type =  float64
[nan]
----------------------
----------------------
column =  CSAA
type =  float64
[nan]
----------------------
----------------------
column =  METDIVA
type =  float64
[nan]
----------------------
----------------------
column =  NECTAA
type =  float64
[nan]
----------------------
----------------------
column =  CNECTAA
type =  float64
[nan]
----------------------
----------------------
column =  NECTADIVA
type =  float64
[nan]
----------------------
----------------------
column =  UAA
type =  float64
[nan]
----------------------
----------------------
column =  CDCURRA
type =  float64
[nan]
----------------------
----------------------
column =  SLDUA
type =  float64
[nan]
----------------------
----------------------
column =  SLDLA
type =  float64
[nan]
----------------------
----------------------
column =  ZCTA5A
type =  float64
[nan]
----------------------
----------------------
column =  SUBMCDA
type =  float64
[nan]
----------------------
----------------------
column =  SDELMA
type =  float64
[nan]
----------------------
----------------------
column =  SDSECA
type =  float64
[nan]
----------------------
----------------------
column =  SDUNIA
type =  float64
[nan]
----------------------
----------------------
column =  PCI
type =  float64
[nan]
----------------------
----------------------
column =  PUMAA
type =  float64
[nan]
----------------------
----------------------
column =  GEOID
type =  object
['05000US51001' '05000US51003' '05000US51005' '05000US51007'
 '05000US51009' '05000US51011' '05000US51013' '05000US51015'
 '05000US51017' '05000US51019' '05000US51021' '05000US51023'
 '05000US51025' '05000US51027' '05000US51029' '05000US51031'
 '05000US51033' '05000US51035' '05000US51036' '05000US51037'
 '05000US51041' '05000US51043' '05000US51045' '05000US51047'
 '05000US51049' '05000US51051' '05000US51053' '05000US51057'
 '05000US51059' '05000US51061' '05000US51063' '05000US51065'
 '05000US51067' '05000US51069' '05000US51071' '05000US51073'
 '05000US51075' '05000US51077' '05000US51079' '05000US51081'
 '05000US51083' '05000US51085' '05000US51087' '05000US51089'
 '05000US51091' '05000US51093' '05000US51095' '05000US51097'
 '05000US51099' '05000US51101' '05000US51103' '05000US51105'
 '05000US51107' '05000US51109' '05000US51111' '05000US51113'
 '05000US51115' '05000US51117' '05000US51119' '05000US51121'
 '05000US51125' '05000US51127' '05000US51131' '05000US51133'
 '05000US51135' '05000US51137' '05000US51139' '05000US51141'
 '05000US51143' '05000US51145' '05000US51147' '05000US51149'
 '05000US51153' '05000US51155' '05000US51157' '05000US51159'
 '05000US51161' '05000US51163' '05000US51165' '05000US51167'
 '05000US51169' '05000US51171' '05000US51173' '05000US51175'
 '05000US51177' '05000US51179' '05000US51181' '05000US51183'
 '05000US51185' '05000US51187' '05000US51191' '05000US51193'
 '05000US51195' '05000US51197' '05000US51199' '05000US51510'
 '05000US51520' '05000US51530' '05000US51540' '05000US51550'
 '05000US51570' '05000US51580' '05000US51590' '05000US51595'
 '05000US51600' '05000US51610' '05000US51620' '05000US51630'
 '05000US51640' '05000US51650' '05000US51660' '05000US51670'
 '05000US51678' '05000US51680' '05000US51683' '05000US51685'
 '05000US51690' '05000US51700' '05000US51710' '05000US51720'
 '05000US51730' '05000US51735' '05000US51740' '05000US51750'
 '05000US51760' '05000US51770' '05000US51775' '05000US51790'
 '05000US51800' '05000US51810' '05000US51820' '05000US51830'
 '05000US51840']
----------------------
----------------------
column =  NAME
type =  object
['Accomack County, Virginia' 'Albemarle County, Virginia'
 'Alleghany County, Virginia' 'Amelia County, Virginia'
 'Amherst County, Virginia' 'Appomattox County, Virginia'
 'Arlington County, Virginia' 'Augusta County, Virginia'
 'Bath County, Virginia' 'Bedford County, Virginia'
 'Bland County, Virginia' 'Botetourt County, Virginia'
 'Brunswick County, Virginia' 'Buchanan County, Virginia'
 'Buckingham County, Virginia' 'Campbell County, Virginia'
 'Caroline County, Virginia' 'Carroll County, Virginia'
 'Charles City County, Virginia' 'Charlotte County, Virginia'
 'Chesterfield County, Virginia' 'Clarke County, Virginia'
 'Craig County, Virginia' 'Culpeper County, Virginia'
 'Cumberland County, Virginia' 'Dickenson County, Virginia'

In [8]:
#Renaming coded columns
new_column_names = {"AM0KE001" :    "Total",
        "AM0KE002" :   "Born in US",
        "AM0KE003":    "Born in US Territory",
        "AM0KE004":    "Born Abroad",
        "AM0KE005":    "Naturalized",
        "AM0KE006":    "Not US Citizen",
}
merged_df.rename(columns=new_column_names, inplace=True)

In [9]:

#Most of the data is encoded, refered to codebooks
#Simplified data by adding all specific below poverty metrics to one column.
povertyCols = ["AM63E002","AM63E003","AM63E004","AM63E005","AM63E006","AM63E007","AM63E008","AM63E009","AM63E010","AM63E011","AM63E012","AM63E013","AM63E014","AM63E015","AM63E016","AM63E017","AM63E018","AM63E019","AM63E020",
                "AM63E021","AM63E022","AM63E023","AM63E024","AM63E025","AM63E026","AM63E027","AM63E028","AM63E029","AM63E030"]
merged_df['Total Pop Below Poverty'] = merged_df[povertyCols].sum(axis=1)
merged_df= merged_df.drop(columns=povertyCols, axis=1)

In [10]:
merged_df.rename(columns={'AM63E001':'Total Pop'}, inplace=True)

In [11]:
#Summing above poverty level data
abovePovertyCols = ["AM63E031","AM63E032","AM63E033","AM63E034","AM63E035","AM63E036","AM63E037","AM63E038","AM63E039","AM63E040","AM63E041","AM63E042","AM63E043","AM63E044","AM63E045","AM63E046","AM63E047","AM63E048","AM63E049",
                "AM63E050","AM63E051","AM63E052","AM63E053","AM63E054","AM63E055","AM63E056","AM63E057","AM63E058","AM63E059"]
merged_df['Total Pop At/Above Poverty'] = merged_df[abovePovertyCols].sum(axis=1)
merged_df = merged_df.drop(columns=abovePovertyCols, axis=1)

In [12]:
#Removing already accounted for poverty by age data
PovertybyAgeCols = ['AM70E001','AM70E002',"AM70E003","AM70E004","AM70E005","AM70E006","AM70E007","AM70E008","AM70E009","AM70E010","AM70E011","AM70E012","AM70E013","AM70E014","AM70E015","AM70E016","AM70E017"]
merged_df = merged_df.drop(columns=PovertybyAgeCols, axis=1)

In [13]:
#Rename Premade Population columns
merged_df.rename(columns={'AM8FE002':'Total Male Pop'}, inplace=True)
merged_df.rename(columns={'AM8FE021':'Total Female Pop'}, inplace=True)
merged_df.rename(columns={'AM8FE028':'Total Young-adult Women'}, inplace=True)
merged_df.rename(columns={'AM8FE009':'Total Young-adult Men'}, inplace=True)
merged_df.rename(columns={'AM8FE031':'Total Midage Women'}, inplace=True)
merged_df.rename(columns={'AM8FE012':'Total Midage Men'}, inplace=True)

In [14]:
#Sum total disabled population
DisabiltyCols = ["AM8FE004","AM8FE007","AM8FE010","AM8FE013","AM8FE016","AM8FE019","AM8FE023","AM8FE026","AM8FE029","AM8FE032","AM8FE035","AM8FE038"]
merged_df['Total Disabled Pop'] = merged_df[DisabiltyCols].sum(axis=1)

In [15]:
#Sum Total Children
ChildCols = ["AM8FE003","AM8FE006","AM8FE022","AM8FE025"]
merged_df['Total Children'] = merged_df[ChildCols].sum(axis=1)

In [16]:
#Sum Total Senior Citizens
SeniorCols = ["AM8FE015","AM8FE018","AM8FE034","AM8FE037"]
merged_df['Total Seniors'] = merged_df[SeniorCols].sum(axis=1)

In [17]:
#Drop all unused columns
colsToDrop= ["AM8FE001","AM8FE003","AM8FE004","AM8FE005","AM8FE006","AM8FE007","AM8FE008","AM8FE010","AM8FE011","AM8FE013","AM8FE014","AM8FE015","AM8FE016","AM8FE017","AM8FE018","AM8FE019","AM8FE020","AM8FE022","AM8FE023","AM8FE024","AM8FE025",
             "AM8FE026","AM8FE027","AM8FE029","AM8FE030","AM8FE032","AM8FE033","AM8FE034","AM8FE035","AM8FE036","AM8FE037","AM8FE038","AM8FE039", "AM9SE001"]
merged_df= merged_df.drop(columns=colsToDrop, axis=1)

In [18]:
for column in merged_df.columns:
  print(column)

Unnamed: 0
year
state
state_po
county_name
county_fips
office
candidate
party
candidatevotes
totalvotes
version
mode
GISJOIN
YEAR
STUSAB
REGIONA
DIVISIONA
STATE
STATEA
COUNTY
COUNTYA
COUSUBA
PLACEA
TRACTA
CONCITA
AIANHHA
RES_ONLYA
TRUSTA
AIHHTLI
AITSCEA
ANRCA
CBSAA
CSAA
METDIVA
NECTAA
CNECTAA
NECTADIVA
UAA
CDCURRA
SLDUA
SLDLA
ZCTA5A
SUBMCDA
SDELMA
SDSECA
SDUNIA
PCI
PUMAA
GEOID
NAME
BTTRA
Total
Born in US
Born in US Territory
Born Abroad
Naturalized
Not US Citizen
Total Pop
Total Male Pop
Total Young-adult Men
Total Midage Men
Total Female Pop
Total Young-adult Women
Total Midage Women
Total Pop Below Poverty
Total Pop At/Above Poverty
Total Disabled Pop
Total Children
Total Seniors

In [19]:
partiallyCleanedDf= merged_df
partiallyCleanedDf.to_csv('./project_voting_group11/data/partiallyCleaned.csv', index=False)

In [20]:
# identifiers and area codes not helpful so only keeping certain columns
Df = partiallyCleanedDf.iloc[:, [4, 8, 9, 10] + list(range(-18, 0))]
# for column in selected_columns.columns:
  # print(column)

# dropping Libertarian and other assuming they are not likely to win
Df = Df[~Df['party'].isin(['LIBERTARIAN', 'OTHER'])]
# Df.head()

In [21]:
# finding net vote by county
counties = Df['county_name'].unique()
county_net_votes = []

for county in counties:
    county_data = Df[Df['county_name'] == county]
    total_dem = county_data[county_data['party'] == 'DEMOCRAT']['candidatevotes'].sum()
    total_rep = county_data[county_data['party'] == 'REPUBLICAN']['candidatevotes'].sum()
    # positive net vote is rep win
    net_vote = np.arcsinh(total_rep - total_dem)  # rescaled for easier prediction fitting
    county_net_votes.append(net_vote)

# only keeping first row for each county bc demographic data repeated for each mode of voting
Df = Df.drop_duplicates(subset='county_name', keep='first')
# dropping party column bc no longer needed
Df = Df.drop(columns=['party'])

# adding in net_vote as new column
Df['netvotes'] = county_net_votes

print(Df.head())
Df.to_csv('./project_voting_group11/data/cleaned_VA_voting.csv', index=False)

   county_name  candidatevotes  totalvotes   Total  Born in US  \
0     ACCOMACK            5495       16962   32560       29524
12   ALBEMARLE           33416       64657  108819       95653
24   ALLEGHANY            1250        8203   15030       14733
36      AMELIA            1719        7894   12970       12694
48     AMHERST            3871       17005   31782       30977

    Born in US Territory  Born Abroad  Naturalized  Not US Citizen  Total Pop  \
0                    119          192          782            1943      32227
12                   469         1470         5183            6044     101147
24                     0          111           91              95      14744
36                     0           97           73             106      12873
48                    71          151          361             222      31002

    ...  Total Midage Men  Total Female Pop  Total Young-adult Women  \
0   ...              5882             16517                     2858
12  ...             18680             56466                    13740
24  ...              2819              7525                     1266
36  ...              2670              6356                     1165
48  ...              6091             16423                     3106

    Total Midage Women  Total Pop Below Poverty  Total Pop At/Above Poverty  \
0                 6474                    19119                       77562
12               20763                    23259                      280182
24                3052                     6945                       37287
36                2667                     4146                       34473
48                6596                    10179                       82827

    Total Disabled Pop  Total Children  Total Seniors   netvotes
0                 4253            6764           7527   8.067149
12                9638           21823          19784 -10.676462
24                2829            2837           3439   8.886271
36                1924            2757           2445   8.692490
48                4888            6213           6516   9.281544

[5 rows x 22 columns]